
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace mh::define::strKey::Scene
{
	STRKEY Scene_Play = "Scene_Play";
	STRKEY Scene_TestCH = "Scene_TestCH";
	STRKEY Scene_TestHJ = "Scene_TestHJ";
	STRKEY Scene_TestJH = "Scene_TestJH";
	STRKEY Scene_TestSB = "Scene_TestSB";
	STRKEY Scene_Title = "Scene_Title";
}
