
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace strKey_Shader
{
	namespace Graphics
	{
		STRKEY UICustomGauge = "UICustomGauge.json";
		STRKEY UIBasic = "UIBasic.json";
		STRKEY UIGauge = "UIGauge.json";
		STRKEY TestCH = "TestCH.json";
		STRKEY TestJH = "TestJH.json";
		STRKEY UIButton = "UIButton.json";
	};
	namespace Compute
	{
		STRKEY CS_TestSB = "CS_TestSB.cso";
	};
}