
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace mh::define::strKey::Texture
{
	STRKEY DefaultSprite_png = "DefaultSprite.png";
	STRKEY evm090_00_01_BML_png = "evm090_00_01_BML.png";
	STRKEY HPBar_png = "HPBar.png";
	STRKEY Light_png = "Light.png";
	STRKEY lurker_SunkenColony__bmp = "lurker(SunkenColony).bmp";
	STRKEY Smile_png = "Smile.png";
	STRKEY test_png = "test.png";
	STRKEY Zelda_png = "Zelda.png";
	namespace Cube
	{
		STRKEY Brick_jpg = "Cube/Brick.jpg";
		STRKEY Brick_N_jpg = "Cube/Brick_N.jpg";
		STRKEY C01_008_Brick_Wall_2048x2048_Bump_Map_jpg = "Cube/C01 008 Brick Wall 2048x2048 Bump Map.jpg";
		STRKEY TILE_01_tga = "Cube/TILE_01.tga";
		STRKEY TILE_01_N_tga = "Cube/TILE_01_N.tga";
		STRKEY TILE_02_tga = "Cube/TILE_02.tga";
		STRKEY TILE_02_N_tga = "Cube/TILE_02_N.tga";
		STRKEY TILE_03_tga = "Cube/TILE_03.tga";
		STRKEY TILE_03_N_tga = "Cube/TILE_03_N.tga";
		STRKEY TILE_ARR_dds = "Cube/TILE_ARR.dds";
		STRKEY TILE_ARRR_dds = "Cube/TILE_ARRR.dds";
		STRKEY TILE_ARR_N_dds = "Cube/TILE_ARR_N.dds";
	}

	namespace FBXTex
	{
		STRKEY SPR_Vill_Warehouse01_Diff_tga = "FBXTex/SPR_Vill_Warehouse01_Diff.tga";
		STRKEY SPR_Vill_Warehouse01_Norm_tga = "FBXTex/SPR_Vill_Warehouse01_Norm.tga";
		STRKEY SPR_Vill_Warehouse01_Spec_tga = "FBXTex/SPR_Vill_Warehouse01_Spec.tga";
		STRKEY SPR_Vill_Warehouse02_Norm_tga = "FBXTex/SPR_Vill_Warehouse02_Norm.tga";
		STRKEY SPR_Vill_Warehouse03_Diff_tga = "FBXTex/SPR_Vill_Warehouse03_Diff.tga";
		STRKEY SPR_Vill_Warehouse03_Spec_tga = "FBXTex/SPR_Vill_Warehouse03_Spec.tga";
	}

	namespace Food_fbm
	{
		STRKEY evm064_00_00_BML_png = "Food.fbm/evm064_00_00_BML.png";
		STRKEY evm170_00_00_BML_png = "Food.fbm/evm170_00_00_BML.png";
		STRKEY evm170_00_00_NM_png = "Food.fbm/evm170_00_00_NM.png";
		STRKEY evm170_00_01_BML_png = "Food.fbm/evm170_00_01_BML.png";
		STRKEY evm170_00_01_NM_png = "Food.fbm/evm170_00_01_NM.png";
		STRKEY evm571_00_00_BML_png = "Food.fbm/evm571_00_00_BML.png";
		STRKEY evm571_00_00_NM_png = "Food.fbm/evm571_00_00_NM.png";
		STRKEY stm730_082_05_BML_png = "Food.fbm/stm730_082_05_BML.png";
		STRKEY stm730_082_05_NM_png = "Food.fbm/stm730_082_05_NM.png";
		STRKEY stm730_117_00_BML_png = "Food.fbm/stm730_117_00_BML.png";
		STRKEY stm730_117_00_NM_png = "Food.fbm/stm730_117_00_NM.png";
		STRKEY stm730_123_00_BML_png = "Food.fbm/stm730_123_00_BML.png";
		STRKEY stm730_123_00_NM_png = "Food.fbm/stm730_123_00_NM.png";
		STRKEY stm730_165_00_BML_png = "Food.fbm/stm730_165_00_BML.png";
		STRKEY stm730_165_00_NM_png = "Food.fbm/stm730_165_00_NM.png";
		STRKEY stm730_170_00_BML_png = "Food.fbm/stm730_170_00_BML.png";
		STRKEY stm730_170_00_NM_png = "Food.fbm/stm730_170_00_NM.png";
		STRKEY stm730_276_00_00_BML_png = "Food.fbm/stm730_276_00_00_BML.png";
		STRKEY stm730_276_00_00_NM_png = "Food.fbm/stm730_276_00_00_NM.png";
		STRKEY stm730_278_00_BML_png = "Food.fbm/stm730_278_00_BML.png";
		STRKEY stm730_278_00_NM_png = "Food.fbm/stm730_278_00_NM.png";
		STRKEY stm740_082_00_BML_png = "Food.fbm/stm740_082_00_BML.png";
		STRKEY stm740_082_00_NM_png = "Food.fbm/stm740_082_00_NM.png";
		STRKEY stm760_024_00_00_BML_png = "Food.fbm/stm760_024_00_00_BML.png";
		STRKEY stm760_024_00_00_NM_png = "Food.fbm/stm760_024_00_00_NM.png";
		STRKEY stm760_024_00_01_BML_png = "Food.fbm/stm760_024_00_01_BML.png";
		STRKEY stm760_024_00_01_NM_png = "Food.fbm/stm760_024_00_01_NM.png";
		STRKEY stm760_025_00_00_BML_png = "Food.fbm/stm760_025_00_00_BML.png";
		STRKEY stm760_025_00_00_NM_png = "Food.fbm/stm760_025_00_00_NM.png";
		STRKEY stm760_025_00_01_BML_png = "Food.fbm/stm760_025_00_01_BML.png";
		STRKEY stm760_025_00_01_NM_png = "Food.fbm/stm760_025_00_01_NM.png";
		STRKEY stm760_026_00_BML_png = "Food.fbm/stm760_026_00_BML.png";
		STRKEY stm760_026_00_NM_png = "Food.fbm/stm760_026_00_NM.png";
	}

	namespace house_fbm
	{
		STRKEY SPR_Vill_Warehouse01_Diff_tga = "house.fbm/SPR_Vill_Warehouse01_Diff.tga";
		STRKEY SPR_Vill_Warehouse01_Norm_tga = "house.fbm/SPR_Vill_Warehouse01_Norm.tga";
		STRKEY SPR_Vill_Warehouse01_Spec_tga = "house.fbm/SPR_Vill_Warehouse01_Spec.tga";
		STRKEY SPR_Vill_Warehouse02_Norm_tga = "house.fbm/SPR_Vill_Warehouse02_Norm.tga";
		STRKEY SPR_Vill_Warehouse03_Diff_tga = "house.fbm/SPR_Vill_Warehouse03_Diff.tga";
		STRKEY SPR_Vill_Warehouse03_Spec_tga = "house.fbm/SPR_Vill_Warehouse03_Spec.tga";
	}

	namespace Monster_fbm
	{
		STRKEY CH_NPC_MOB_Anashar_A01_Lower_D_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Lower_D_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Lower_N_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Lower_N_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Lower_SP_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Lower_SP_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Shoulder_D_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Shoulder_D_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Shoulder_N_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Shoulder_N_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Shoulder_SP_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Shoulder_SP_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Upper_D_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Upper_D_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Upper_N_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Upper_N_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_A01_Upper_SP_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_A01_Upper_SP_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_Weapon_A01_D_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_Weapon_A01_D_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_Weapon_A01_N_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_Weapon_A01_N_KGW.tga";
		STRKEY CH_NPC_MOB_Anashar_Weapon_A01_SP_KGW_tga = "Monster.fbm/CH_NPC_MOB_Anashar_Weapon_A01_SP_KGW.tga";
	}

	namespace noise
	{
		STRKEY noise_01_png = "noise/noise_01.png";
		STRKEY noise_02_png = "noise/noise_02.png";
		STRKEY noise_03_jpg = "noise/noise_03.jpg";
	}

	namespace particle
	{
		STRKEY AlphaCircle_png = "particle/AlphaCircle.png";
		STRKEY Bubbles50px_png = "particle/Bubbles50px.png";
		STRKEY Bubbles99px_png = "particle/Bubbles99px.png";
		STRKEY CartoonSmoke_png = "particle/CartoonSmoke.png";
		STRKEY HardCircle_png = "particle/HardCircle.png";
		STRKEY HardRain_png = "particle/HardRain.png";
		STRKEY smokeparticle_png = "particle/smokeparticle.png";
		STRKEY Snow50px_png = "particle/Snow50px.png";
		STRKEY Sparks_png = "particle/Sparks.png";
	}

	namespace Player_Default_fbm
	{
		STRKEY DXT1_cage003_BML_dds = "Player_Default.fbm/DXT1_cage003_BML.dds";
		STRKEY DXT1_cage003_EM_dds = "Player_Default.fbm/DXT1_cage003_EM.dds";
		STRKEY DXT1_hand008_BML_dds = "Player_Default.fbm/DXT1_hand008_BML.dds";
		STRKEY DXT1_knife001_BML_dds = "Player_Default.fbm/DXT1_knife001_BML.dds";
		STRKEY DXT1_m_arm039_0001_BML_dds = "Player_Default.fbm/DXT1_m_arm039_0001_BML.dds";
		STRKEY DXT1_m_arm039_0001_XM_dds = "Player_Default.fbm/DXT1_m_arm039_0001_XM.dds";
		STRKEY DXT1_m_body039_0001_BML_dds = "Player_Default.fbm/DXT1_m_body039_0001_BML.dds";
		STRKEY DXT1_m_body039_0001_XM_dds = "Player_Default.fbm/DXT1_m_body039_0001_XM.dds";
		STRKEY DXT1_m_helm039_0001_BML_dds = "Player_Default.fbm/DXT1_m_helm039_0001_BML.dds";
		STRKEY DXT1_m_helm039_0001_XM_dds = "Player_Default.fbm/DXT1_m_helm039_0001_XM.dds";
		STRKEY DXT1_m_leg039_0001_BML_dds = "Player_Default.fbm/DXT1_m_leg039_0001_BML.dds";
		STRKEY DXT1_m_leg039_0001_XM_dds = "Player_Default.fbm/DXT1_m_leg039_0001_XM.dds";
		STRKEY DXT1_m_slinger039_0000_BML_dds = "Player_Default.fbm/DXT1_m_slinger039_0000_BML.dds";
		STRKEY DXT1_m_slinger039_0000_XM_dds = "Player_Default.fbm/DXT1_m_slinger039_0000_XM.dds";
		STRKEY DXT1_m_wst039_0001_BML_dds = "Player_Default.fbm/DXT1_m_wst039_0001_BML.dds";
		STRKEY DXT1_m_wst039_0001_XM_dds = "Player_Default.fbm/DXT1_m_wst039_0001_XM.dds";
	}

	namespace Res1
	{
		namespace GrayCrystal_fbm
		{
			STRKEY stm520_012_01_00_BML_png = "Res1/GrayCrystal.fbm/stm520_012_01_00_BML.png";
			STRKEY stm520_012_01_00_NM_png = "Res1/GrayCrystal.fbm/stm520_012_01_00_NM.png";
		}

	}

}
