
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace mh::define::strKey::Scene
{
	STRKEY Scene_Play = "Scene_Play";
	STRKEY Scene_Title = "Scene_Title";
}
