
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace strKey_Shader
{
	namespace Graphics
	{
		STRKEY CH = "CH.json";
		STRKEY Example = "Example.json";
		STRKEY HJ = "HJ.json";
		STRKEY JH = "JH.json";
		STRKEY TestCH = "TestCH.json";
		STRKEY SB = "SB.json";
		STRKEY TestJH = "TestJH.json";
	};
	namespace Compute
	{
		STRKEY CS_TestSB = "CS_TestSB.cso";
	};
}