
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace mh::define::strKey::Texture
{
	STRKEY DefaultSprite_png = "DefaultSprite.png";
	STRKEY evm090_00_01_BML_png = "evm090_00_01_BML.png";
	STRKEY HPBar_png = "HPBar.png";
	STRKEY Light_png = "Light.png";
	STRKEY Smile_png = "Smile.png";
	STRKEY test_png = "test.png";
	STRKEY Zelda_png = "Zelda.png";
	namespace Cube
	{
		STRKEY Brick_jpg = "Cube/Brick.jpg";
		STRKEY Brick_N_jpg = "Cube/Brick_N.jpg";
		STRKEY C01_008_Brick_Wall_2048x2048_Bump_Map_jpg = "Cube/C01 008 Brick Wall 2048x2048 Bump Map.jpg";
		STRKEY TILE_01_tga = "Cube/TILE_01.tga";
		STRKEY TILE_01_N_tga = "Cube/TILE_01_N.tga";
		STRKEY TILE_02_tga = "Cube/TILE_02.tga";
		STRKEY TILE_02_N_tga = "Cube/TILE_02_N.tga";
		STRKEY TILE_03_tga = "Cube/TILE_03.tga";
		STRKEY TILE_03_N_tga = "Cube/TILE_03_N.tga";
		STRKEY TILE_ARR_dds = "Cube/TILE_ARR.dds";
		STRKEY TILE_ARRR_dds = "Cube/TILE_ARRR.dds";
		STRKEY TILE_ARR_N_dds = "Cube/TILE_ARR_N.dds";
	}

	namespace FBXTex
	{
		STRKEY SPR_Vill_Warehouse01_Diff_tga = "FBXTex/SPR_Vill_Warehouse01_Diff.tga";
		STRKEY SPR_Vill_Warehouse01_Norm_tga = "FBXTex/SPR_Vill_Warehouse01_Norm.tga";
		STRKEY SPR_Vill_Warehouse01_Spec_tga = "FBXTex/SPR_Vill_Warehouse01_Spec.tga";
		STRKEY SPR_Vill_Warehouse02_Norm_tga = "FBXTex/SPR_Vill_Warehouse02_Norm.tga";
		STRKEY SPR_Vill_Warehouse03_Diff_tga = "FBXTex/SPR_Vill_Warehouse03_Diff.tga";
		STRKEY SPR_Vill_Warehouse03_Spec_tga = "FBXTex/SPR_Vill_Warehouse03_Spec.tga";
	}

	namespace noise
	{
		STRKEY noise_01_png = "noise/noise_01.png";
		STRKEY noise_02_png = "noise/noise_02.png";
		STRKEY noise_03_jpg = "noise/noise_03.jpg";
	}

	namespace particle
	{
		STRKEY AlphaCircle_png = "particle/AlphaCircle.png";
		STRKEY Bubbles50px_png = "particle/Bubbles50px.png";
		STRKEY Bubbles99px_png = "particle/Bubbles99px.png";
		STRKEY CartoonSmoke_png = "particle/CartoonSmoke.png";
		STRKEY HardCircle_png = "particle/HardCircle.png";
		STRKEY HardRain_png = "particle/HardRain.png";
		STRKEY smokeparticle_png = "particle/smokeparticle.png";
		STRKEY Snow50px_png = "particle/Snow50px.png";
		STRKEY Sparks_png = "particle/Sparks.png";
	}

}
