
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace mh::define::strKey::Script
{
	STRKEY Script_CameraMove = "Script_CameraMove";
	STRKEY Script_Player = "Script_Player";
	STRKEY Script_UIBase = "Script_UIBase";
	STRKEY Script_UIButton = "Script_UIButton";
	STRKEY Script_UIGauge = "Script_UIGauge";
}
