
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace strKey_Shader
{
	namespace Graphics
	{
		STRKEY Test = "Test.json";
		STRKEY TestCH = "TestCH.json";
		STRKEY TestJH = "TestJH.json";
	};
	namespace Compute
	{
		STRKEY CS_Test = "CS_Test.cso";
		STRKEY CS_TestSB = "CS_TestSB.cso";
	};
}